<?xml version="1.0" encoding="utf-8"?><Database Name="TanDB" Class="AuthorityDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SETTAN;Initial Catalog=TanDB;Integrated Security=True" SettingsObjectName="Farm.Authority.Properties.Settings" SettingsPropertyName="TanDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbRole" Member="tbRole">
    <Type Name="tbRole">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="disabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="tbRole_tbUser" Member="tbUser" ThisKey="ID" OtherKey="roleID" Type="tbUser" />
      <Association Name="tbRole_tbPermission" Member="tbPermission" ThisKey="ID" OtherKey="roleID" Type="tbPermission" />
    </Type>
  </Table>
  <Table Name="dbo.tbUser" Member="tbUser">
    <Type Name="tbUser">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="userName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="userPassword" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="roleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="logTimes" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="lastLogTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="lastLogIP" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="tbUser_Purview" Member="Purview" ThisKey="ID" OtherKey="userID" Type="Purview" />
      <Association Name="tbRole_tbUser" Member="tbRole" ThisKey="roleID" OtherKey="ID" Type="tbRole" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbPermission" Member="tbPermission">
    <Type Name="tbPermission">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="roleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="controllerName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="actionName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="tbRole_tbPermission" Member="tbRole" ThisKey="roleID" OtherKey="ID" Type="tbRole" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Purview" Member="Purview">
    <Type Name="Purview">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="areaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tbUser_Purview" Member="tbUser" ThisKey="userID" OtherKey="ID" Type="tbUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="Users">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="userID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="userName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="userPassword" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="roleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="logTimes" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="lastLogTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="lastLogIP" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="roleName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Role" Member="Role">
    <Type Name="Role">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="disabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="role" Member="role1" Type="System.Data.Linq.Binary" DbType="VarBinary(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>